// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.18.0
// source: medium/grpc_testing/proto/authority.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameFilterRe     string   `protobuf:"bytes,1,opt,name=name_filter_re,json=nameFilterRe,proto3" json:"name_filter_re,omitempty"`
	DatacenterFilter []string `protobuf:"bytes,2,rep,name=datacenter_filter,json=datacenterFilter,proto3" json:"datacenter_filter,omitempty"`
}

func (x *ServersReq) Reset() {
	*x = ServersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medium_grpc_testing_proto_authority_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServersReq) ProtoMessage() {}

func (x *ServersReq) ProtoReflect() protoreflect.Message {
	mi := &file_medium_grpc_testing_proto_authority_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServersReq.ProtoReflect.Descriptor instead.
func (*ServersReq) Descriptor() ([]byte, []int) {
	return file_medium_grpc_testing_proto_authority_proto_rawDescGZIP(), []int{0}
}

func (x *ServersReq) GetNameFilterRe() string {
	if x != nil {
		return x.NameFilterRe
	}
	return ""
}

func (x *ServersReq) GetDatacenterFilter() []string {
	if x != nil {
		return x.DatacenterFilter
	}
	return nil
}

type ServerMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ServerMsg) Reset() {
	*x = ServerMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_medium_grpc_testing_proto_authority_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMsg) ProtoMessage() {}

func (x *ServerMsg) ProtoReflect() protoreflect.Message {
	mi := &file_medium_grpc_testing_proto_authority_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMsg.ProtoReflect.Descriptor instead.
func (*ServerMsg) Descriptor() ([]byte, []int) {
	return file_medium_grpc_testing_proto_authority_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_medium_grpc_testing_proto_authority_proto protoreflect.FileDescriptor

var file_medium_grpc_testing_proto_authority_proto_rawDesc = []byte{
	0x0a, 0x29, 0x6d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x22, 0x5f, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x24, 0x0a, 0x0e, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x5f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x61, 0x6d, 0x65, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x64, 0x61, 0x74, 0x61, 0x63,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x10, 0x64, 0x61, 0x74, 0x61, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x22, 0x1f, 0x0a, 0x09, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73,
	0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x61, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x74, 0x79, 0x12, 0x54, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x12, 0x22, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x1a, 0x21, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x30, 0x01, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x6f, 0x68, 0x6e, 0x73, 0x69, 0x69, 0x6c, 0x76,
	0x65, 0x72, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_medium_grpc_testing_proto_authority_proto_rawDescOnce sync.Once
	file_medium_grpc_testing_proto_authority_proto_rawDescData = file_medium_grpc_testing_proto_authority_proto_rawDesc
)

func file_medium_grpc_testing_proto_authority_proto_rawDescGZIP() []byte {
	file_medium_grpc_testing_proto_authority_proto_rawDescOnce.Do(func() {
		file_medium_grpc_testing_proto_authority_proto_rawDescData = protoimpl.X.CompressGZIP(file_medium_grpc_testing_proto_authority_proto_rawDescData)
	})
	return file_medium_grpc_testing_proto_authority_proto_rawDescData
}

var file_medium_grpc_testing_proto_authority_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_medium_grpc_testing_proto_authority_proto_goTypes = []interface{}{
	(*ServersReq)(nil), // 0: grpc_testing.authority.ServersReq
	(*ServerMsg)(nil),  // 1: grpc_testing.authority.ServerMsg
}
var file_medium_grpc_testing_proto_authority_proto_depIdxs = []int32{
	0, // 0: grpc_testing.authority.Authority.Servers:input_type -> grpc_testing.authority.ServersReq
	1, // 1: grpc_testing.authority.Authority.Servers:output_type -> grpc_testing.authority.ServerMsg
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_medium_grpc_testing_proto_authority_proto_init() }
func file_medium_grpc_testing_proto_authority_proto_init() {
	if File_medium_grpc_testing_proto_authority_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_medium_grpc_testing_proto_authority_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_medium_grpc_testing_proto_authority_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_medium_grpc_testing_proto_authority_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_medium_grpc_testing_proto_authority_proto_goTypes,
		DependencyIndexes: file_medium_grpc_testing_proto_authority_proto_depIdxs,
		MessageInfos:      file_medium_grpc_testing_proto_authority_proto_msgTypes,
	}.Build()
	File_medium_grpc_testing_proto_authority_proto = out.File
	file_medium_grpc_testing_proto_authority_proto_rawDesc = nil
	file_medium_grpc_testing_proto_authority_proto_goTypes = nil
	file_medium_grpc_testing_proto_authority_proto_depIdxs = nil
}
